version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper:/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    # networks:
    #   - app-tier
    ports:
      - "9094:9094"
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      # - KAFKA_CFG_BROKER_ID=1
      # - KAFKA_CFG_NODE_ID=1
      # - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=micro
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3306:3306
    volumes: 
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin

  # myapp:
  #   image: consumer
  #   container_name: consumer
  #   ports: 
  #     - 3000:3000
  #   networks:
  #     - app-tier
  #     - mysql-phpmyadmin
  #   depends_on:
  #     - kafka

networks:
  mysql-phpmyadmin:
  # app-tier:
  #   driver: bridge
